### PR TITLE
add a bunch of GOST ciphers

### PR DESCRIPTION
**Pull request by jschauma**
See also: https://tools.ietf.org/id/draft-smyshlyaev-tls12-gost-suites-00.html

### CODE REVIEW

**Comment by jmhodges** [comment]
Hm, the only changes I see here are commented out new suites. Did you mean to uncomment them?

**Comment by jschauma** [comment]
Jeff Hodges <notifications@github.com> wrote:
> Hm, the only changes I see here are commented out new suites. Did you mean to uncomment them?

There should be two uncommented new suites:

+	0x0081: "TLS_GOST2001-GOST89-GOST89",

+	0xFF85: "TLS_GOST2012256-GOST89-GOST89",

**Comment by jmhodges** [comment]
Oh, you’re right. What’s up with the other ones?

**Comment by jschauma** [comment]
Jeff Hodges <notifications@github.com> wrote:
> Oh, you?re right. What?s up with the other ones?

When I searched for the codes, those came up elsewhere, but I wasn't
able to confirm definitely whether those names are correct.  If you
prefer not to have junk comments, I can nuke those from the PR.

**Comment by jschauma** [comment]
No prob.  Last commit removes the commented out ciphers.

**Comment by jmhodges** [comment]
Thanks! Deploy will happen automatically in a few minutes

**Pull request merged**
